/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ChampionshipController;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.*;
import model.ChampionshipModel;

/**
 *
 * @author fabri
 */
public class MainScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());
    private int champ_id;
    
    public MainScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainDeskPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ChampMenu = new javax.swing.JMenu();
        createChampItem = new javax.swing.JMenuItem();
        selectChampItem = new javax.swing.JMenuItem();
        manageChampItem = new javax.swing.JMenuItem();
        TeamsMenu = new javax.swing.JMenu();
        addTeamItem = new javax.swing.JMenuItem();
        manageTeamItem = new javax.swing.JMenuItem();
        PartcipantMenu = new javax.swing.JMenu();
        addParticipantItem = new javax.swing.JMenuItem();
        manageParticipantItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout MainDeskPaneLayout = new javax.swing.GroupLayout(MainDeskPane);
        MainDeskPane.setLayout(MainDeskPaneLayout);
        MainDeskPaneLayout.setHorizontalGroup(
            MainDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        MainDeskPaneLayout.setVerticalGroup(
            MainDeskPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 486, Short.MAX_VALUE)
        );

        ChampMenu.setText("Championship");

        createChampItem.setText("Create");
        createChampItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createChampItemActionPerformed(evt);
            }
        });
        ChampMenu.add(createChampItem);

        selectChampItem.setText("Select");
        selectChampItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectChampItemActionPerformed(evt);
            }
        });
        ChampMenu.add(selectChampItem);

        manageChampItem.setText("Manage");
        manageChampItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageChampItemActionPerformed(evt);
            }
        });
        ChampMenu.add(manageChampItem);

        jMenuBar1.add(ChampMenu);

        TeamsMenu.setText("Teams");

        addTeamItem.setText("Add");
        addTeamItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTeamItemActionPerformed(evt);
            }
        });
        TeamsMenu.add(addTeamItem);

        manageTeamItem.setText("Manage");
        manageTeamItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageTeamItemActionPerformed(evt);
            }
        });
        TeamsMenu.add(manageTeamItem);

        jMenuBar1.add(TeamsMenu);

        PartcipantMenu.setText("Participants");

        addParticipantItem.setText("Add");
        addParticipantItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addParticipantItemActionPerformed(evt);
            }
        });
        PartcipantMenu.add(addParticipantItem);

        manageParticipantItem.setText("Manage");
        manageParticipantItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageParticipantItemActionPerformed(evt);
            }
        });
        PartcipantMenu.add(manageParticipantItem);

        jMenuBar1.add(PartcipantMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDeskPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainDeskPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createChampItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createChampItemActionPerformed
        AddChampFrame aCF = new AddChampFrame();
        this.MainDeskPane.add(aCF);
        aCF.setVisible(true);
    }//GEN-LAST:event_createChampItemActionPerformed

    private void selectChampItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectChampItemActionPerformed
        ChampionshipController champC = new ChampionshipController();
        try{
            ArrayList<ChampionshipModel> list = champC.listChampioship();
            
            JComboBox<String> comboBox = new JComboBox<>();
            DefaultComboBoxModel dcm = (DefaultComboBoxModel) comboBox.getModel();
            dcm.removeAllElements();
            for(ChampionshipModel champM: list){
                dcm.addElement(champM.getId());
            }
            JPanel panel = new JPanel();
            panel.add(new JLabel("Select an option:"));
            panel.add(comboBox);

            int result = JOptionPane.showConfirmDialog(
                    null, 
                    panel,
                    "Choose an Option", 
                    JOptionPane.OK_CANCEL_OPTION, 
                    JOptionPane.PLAIN_MESSAGE
            );

            if (result == JOptionPane.OK_OPTION) {
                this.champ_id = (Integer) comboBox.getSelectedItem();
                System.out.println(champ_id);
            } else {
                JOptionPane.showMessageDialog(null, "Selection cancelled.");
            }
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error with DB {"+e.toString()+"}");
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro {"+e.toString()+"}");
        }
    }//GEN-LAST:event_selectChampItemActionPerformed

    private void manageChampItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageChampItemActionPerformed
        ManageChampFrame mCF = new ManageChampFrame();
        this.MainDeskPane.add(mCF);
        mCF.setVisible(true);
    }//GEN-LAST:event_manageChampItemActionPerformed

    private void addTeamItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTeamItemActionPerformed
        AddTeamFrame aTF = new AddTeamFrame(this.champ_id);
        this.MainDeskPane.add(aTF);
        aTF.setVisible(true);
    }//GEN-LAST:event_addTeamItemActionPerformed

    private void manageTeamItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageTeamItemActionPerformed
        ManageTeamFrame mTF = new ManageTeamFrame(this.champ_id);
        this.MainDeskPane.add(mTF);
        mTF.setVisible(true);
    }//GEN-LAST:event_manageTeamItemActionPerformed

    private void addParticipantItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addParticipantItemActionPerformed
        AddParticipantFrame aPF = new AddParticipantFrame(this.champ_id);
        this.MainDeskPane.add(aPF);
        aPF.setVisible(true);
    }//GEN-LAST:event_addParticipantItemActionPerformed

    private void manageParticipantItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageParticipantItemActionPerformed
        ManageParticipantsFrame mPF = new ManageParticipantsFrame(this.champ_id);
        this.MainDeskPane.add(mPF);
        mPF.setVisible(true);
    }//GEN-LAST:event_manageParticipantItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ChampMenu;
    private javax.swing.JDesktopPane MainDeskPane;
    private javax.swing.JMenu PartcipantMenu;
    private javax.swing.JMenu TeamsMenu;
    private javax.swing.JMenuItem addParticipantItem;
    private javax.swing.JMenuItem addTeamItem;
    private javax.swing.JMenuItem createChampItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem manageChampItem;
    private javax.swing.JMenuItem manageParticipantItem;
    private javax.swing.JMenuItem manageTeamItem;
    private javax.swing.JMenuItem selectChampItem;
    // End of variables declaration//GEN-END:variables
}
